//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.KitapOneriler = new HashSet<KitapOneriler>();
        }
    
        public int Id { get; set; }
        public string KitapAd { get; set; }
        public Nullable<int> KitapTur { get; set; }
        public Nullable<int> KitapKonu { get; set; }
        public string KitapYazar { get; set; }
        public Nullable<int> KitapDil { get; set; }
        public Nullable<int> KitapYıl { get; set; }
        public Nullable<int> KitapSayfa { get; set; }
        public string KitapFoto { get; set; }
        public Nullable<bool> KitapDoluBos { get; set; }
    
        public virtual Kitap_Dili Kitap_Dili { get; set; }
        public virtual Kitap_Konusu Kitap_Konusu { get; set; }
        public virtual Kitap_Turu Kitap_Turu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapOneriler> KitapOneriler { get; set; }
    }
}
